### ISSUE TITLE
new features suggestions around "helper" windows

### ISSUE THREAD

**Issue by tardypad** [mhinz/vim-sayonara#10]
Hi,

I've added a couple of specific handling around Sayonara in my own config.
I just share it here in case you might think any of them can make its way directly in the plugin (probably with extra config variables)
And this is also just to raise some limitations of the current "smart" closing.

https://github.com/tardypad/dotfiles/commit/e42d0ea51c97923337950c28e9e124e414a53f26

They both relate to "confusing" behaviors with what I would call "helper" windows
(windows that display a buffer not meant to be edited: files tree, undo trees, tags,...)

* this 1st one "closing of helper windows"

```vim
  " we don't want to delete the buffer
  " for some specific ones
  " but just close the window
  if &filetype == 'nerdtree'
    NERDTreeClose
    return
  elseif &filetype == 'undotree'
    UndotreeHide
    return
  endif
```
The thing is for NERDTree for example, I don't want the buffer to be deleted, otherwise its current state gets lost (which tree items are open and such)
It better just gets hidden

* the 2nd one "closing of unique editable window"

```vim
  let editable_windows_count =
    \ len(filter(tabpagebuflist(), 'buflisted(v:val)'))

  " we don't want to close the window
  " if it's the last "editable" ones among several
  " but just delete the buffer
  if editable_windows_count == 1
      \ && winnr('$') > 1
      \ && buflisted(bufnr('%'))
    Sayonara!
    return
  endif
```

If my current windows are
```
+--------+----------------------+----------+
|        |                      |          |
|        |                      |          |
|  NERD  |         code         | undotree |
|        |                      |          |
|        |                      |          |
|        |                      +----------+
|        |                      |          |
|        |                      |   diff   |
|        |                      |          |
+--------+----------------------+----------+
```
and I'm editing the code window with multiple file buffers, I don't want this window to be closed (thus leaving vim with just "helper" windows) but just the buffer to be deleted (and the next one to get displayed)

I know this is a case where I can directly use `Sayonara!` but in my mind I use this command only when I explicitly want to keep the file splits and just close the buffer.
The problem here is that the other "helper" windows don't feel as being splits and so it gets confusing

With this extra check, the code window will only get closed once there is no more listed buffers.

**Comment by mhinz** [comment]
First of all, thanks for the feedback!

**(1)**

These "plugin buffers" (often have `&buftype == 'nofile'`) could do anything, so this plugin can't foresee what's best to do. But as you outlined already, I could add an option which is a dictionary that takes a filetype as key and a command (or multiple) as value. E.g.

```viml
let g:sayonara_filetypes = {
   \ 'nerdtree': 'NERDTreeClose',
   \ 'undotree': 'echomsg "Closing Undotree" | UndotreeHide',
   \ }
```

Then the plugin would simply do:

```viml
if has_key(get(g:, 'sayonara_filetypes', {}), &filetype)
  execute g:sayonara_filetypes[&filetype]
  return
endif
```

**(2)**

I understand what your code snippet does, but I'm not sure what do you want to see added to the plugin. :-) Without checking, closing the last listed buffer should attempt to quit Vim and not leave you with only those plugin buffers.

If this is not happening it should.

**Comment by tardypad** [comment]
**(1)**

Yes I was thinking of something in that direction
I was just not sure if this check should better be done on the filetype or the buffer name or something else.

**(2)**

Well I was thinking that there could be an option such as `keep_last_editable_window_open` that would execute such a snippet to close the listed buffers first, if we are in that last editable window
Otherwise we are left with only plugin buffers displayed **but** with still hidden listed buffers


Again, these were indeed merely feedbacks
So if you feel those features don't have their place in the plugin for any reason, I understand that you discard them :)

**Comment by mhinz** [comment]
Okay, one step after the other. I'll introduce `g:signify_filestypes` first. If the need for `g:signify_buffernames` ever comes up, it will be easy to add.

**Comment by mhinz** [comment]
Okay, I decided to skip on **(2)**. :-)

Adding what you want would be easy, but it would be hard explain to someone who's not using the same workflow. (Most people get confused about `listed`/`loaded`/`active`/`hidden` etc. already.)

Currently the behaviour is easy to explain: `:Sayonara` closes the window (except it's the last window), `:Sayonara!` does not. Adding options like `g:sayonara_keep_last_editable_window_open` would only make it harder to reason about what `:Sayonara` would do in any given case.

---

Depending on what you want, I could help making your custom solution a bit easier, though. Currently `:Sayonara` calls the internal `s:sayonara()` which kicks off the plugin logic.

I could make that function global, so you could have a 1:1 replacement in your vimrc like this:

```vim
" The vimrc always get sourced first. Use an autocmd to set our custom :Sayonara,
" since sourcing the sayonara plugin afterwards will overwrite it with its own version
" otherwise.
autocmd VimEnter *
      \ command! -nargs=0 -complete=buffer -bang -bar Sayonara call s:sayonara(<bang>0)

function! s:sayonara(bang) abort
  let preserve =
        \ a:bang || (len(filter(tabpagebuflist(), 'buflisted(v:val)')) == 1
        \            && winnr('$') > 1
        \            && buflisted(bufnr('%')))
  " Sayonara(1) preserves the window, Sayonara(0) closes it.
  call Sayonara(preserve)
endfunction
```

This is only needed if you want to keep `:Sayonara!` (behaves as before) and `:Sayonara` (takes your workflow into account).

**Comment by mhinz** [comment]
Okay, the issue itself should be "solved", so I'm closing this.

Thanks for your feedback!

**Comment by tardypad** [comment]
Sorry for the delay

Thanks for adding the special filetypes handling
I've just changed my config to use it and it works good :+1: 

I understand your point for **(2)**
No need to make that function global just for me then, I'll keep my own custom function

Thanks!
