### ISSUE TITLE
Don't fall back on quickfix or location list

### ISSUE THREAD

**Issue by teto** [mhinz/vim-sayonara#11]
Hi,

Here is some idea in case you feeling bored :) 
I usually work with one 'main' window + the quickfix window. When closing the main window, the quickfix becomes the main window which usually leads me to insult either a coworker or myself when alone. 
```
______
|     |
| main|
|_____|
| qf  |
|_____|
```
When focusing "main" and calling sayonara, it becomes (logic):
```
______
|    |
|    |
| qf |
|    |
|____|
```

Would it be doable to have a setting or a filter to ignore some windows (quickfix mostly) so that calling sayonara on "buf1" ?
```
______
|     |
| buf1|
|_____|
| qf  |
|_____|
```
becomes
```
______
|      |
| buf42|
|_____|
| qf  |
|_____|

```
Cheers

**Comment by mhinz** [comment]
Then don't close the window and use `:Sayonara!` instead? :-)

I guess most people probably want to map `:Sayonara!` as their default action and `:Sayonara` only when they actually intend to quit the window.

**Comment by teto** [comment]
Once again I feel stupid. For my defense, I first tried sayonara's help but it was apparently not available due to vim-plug failing to update another plugin. Problem fixed ty
