### ISSUE TITLE
Error when starting due to `complete` command setting nargs=0

### ISSUE THREAD

**Issue by sunjon** [mhinz/vim-sayonara#20]
> vim-patch:8.2.3141: no error when using :complete for :command without -nargs

>Problem: No error when using :complete for :command without -nargs.
> Solution: Give an error. (Martin Tournoij, closes vim/vim#8544, closes vim/vim#8541)
> vim/vim@de69a73

After this this patch was merged, the plugin now breaks on startup:
```
line  187:                                                                                                                                  
E1208: -complete used without -nargs 
```

**Comment by Drezil** [comment]
#19 fixes this. (#17 and #18 do so as well, but differently).
