### ISSUE TITLE
Sayonara! throws error in CmdLineWindow

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-sayonara#5]
https://github.com/mhinz/vim-sayonara/commit/a83a29a1049cbe902adf0267591600e7c0762488  does not work over here, `q::Sayonara!<cr>` gives

```
Error detected while processing function <SNR>206_sayonara[9]..71[6]..72:
line   19:
E11: Invalid in command-line window; <CR> executes, CTRL-C quits:     buffer! #
```

**Comment by mhinz** [comment]
Thanks, apparently I only tested it with `:Sayonara`, since you can't preserve special windows easily and emulating it is not really worth it, IMHO.

`:Sayonara!` should closes such windows properly now.

**Comment by Konfekt** [comment]
Thanks, that was fast. The error is no longer thrown.

`Sayonara!` used to leave a window of the same size as the quickfix window open before. That's no longer happening. Fine with me, but perhaps not what was intended.

**Comment by mhinz** [comment]
But that should only happen with "special windows" like the commandline window, `:copen` and `:lopen`.

Unfortunately you can't change to other buffers from the commandline window and preserving `:copen` or `:lopen` is rarely what you want.

**Comment by Konfekt** [comment]
Yep, that's why it was all the more surprising that it previously kept the `quickfix-windows`. It's fine this way, just to serve notice that this commit didn't throw out the child with the bathwater.

**Comment by mhinz** [comment]
Oh, right, I kind of misread your previous response.

Thanks for the feedback!
