### ISSUE TITLE
E481: No range allowed

### ISSUE THREAD

**Issue by sunaku** [mhinz/vim-sayonara#6]
Please add support for ranges so we can completely replace `bdelete` with `Sayonara`:

```
                :.,$-bdelete   "delete buffers from the current one to
                               " last but one
                :%bdelete      " delete all buffers
```

Thanks for your consideration.

**Comment by mhinz** [comment]
Okay, I'll see what I can do without rewriting everything to take arbitrary buffers instead of just acting on the current window.

**Comment by mhinz** [comment]
@sunaku What would be the expected behaviour?

`:Sayonara` is supposed to handle windows, so if range `:1,4` is given, but only buffer 2 is shown in a window in the current tabpage (buffer 1, 3, and 4 are hidden), only that window is closed with `:Sayonara`?

**Comment by sunaku** [comment]
Yes, that seems like a reasonable solution. :+1:

**Comment by mhinz** [comment]
I know this is a very late response, but I decided against this feature for keeping the plugin as simple as possible.

Thanks for the suggestion anyway.
