### ISSUE TITLE
Closes vim even when buffers are still open

### ISSUE THREAD

**Issue by teto** [mhinz/vim-sayonara#8]
Using neovim and sayonara master:
1. open several buffers
2. open a quickfix with :copen
3. focus the other window that is not the quickfix
4. calls sayonara on that buffer, now the quickfix is _fullscreen_
5. calls sayonara on the quickfix, it closes vim while you still have buffers open.

It doesn't seem like an appropriate behavior to me, is it ?
I haven't tested with a nude .vimrc but I shouldn't have anything interfering with sayonara (I tried to use nvim -u NORC and then :packadd but vim-sayonara could not be loaded)

**Comment by mhinz** [comment]
Hmm, I can reproduce this. Let me look into it.

**Comment by mhinz** [comment]
Should work now!

**Comment by teto** [comment]
you are the best :+1:
