### ISSUE TITLE
can't close last window

### ISSUE THREAD

**Issue by alok** [mhinz/vim-sayonara#9]
If windows like netrw, help, (neo)man page are last buffer, can't close them to quit (neo)vim.

**Comment by mhinz** [comment]
Steps?

```
$ nvim
:Man printf
:only
:Sayonara
```

This approach works for all the buffer types mentioned above.

**Comment by alok** [comment]
I just realized that this is an issue with the `q` hotkey, which has
buffer-local mappings in all those filetypes. `Sayonara` is never
actually invoked.

On 01.28.17, Marco Hinz wrote:
>Steps?
>
>```
>$ nvim
>:Man printf
>:only
>:Sayonara
>```
>
>This approach works for for all the buffer types mentioned above.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mhinz/vim-sayonara/issues/9#issuecomment-275890522

-- 
-- Alok

**Comment by alok** [comment]
On a related note, if I run `:Sayonara` with or without exclamation mark on a `netrw` buffer that's the only open buffer, it has no effect.

**Comment by mhinz** [comment]
Repro steps?

When I open a single netrw buffer, e.g. `vim /tmp`, then `:Sayonara` closes Vim and `:Sayonara!` deletes the netrw buffer and creates a scratch buffer.

Is it working differently for you?

**Comment by alok** [comment]
In neovim, I don't get that behavior. It has no effect on the buffer.

-- Alok

**Comment by mhinz** [comment]
Hmm, maybe there are netrw options or autocmds interfering?

Does `:Sayonara` quit Neovim when started like this? (For me it does.)

```
$ nvim -u NORC --cmd 'set rtp+=~/.config/nvim/bundle/vim-sayonara/' /tmp
```

(I tried v0.1.7 and master.)

**Comment by alok** [comment]
That works, so it's something else. Time to go through my config...
